
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "hello world",
    "owner": "inbar",
    "content": "hadar"
}

###

GET http://localhost:3000/posts

###

PUT http://localhost:3000/posts/673ea14a273b7adae44c7873
Content-Type: application/json

{
    "title": "hii",
    "owner": "hila",
    "content": "shalom"
}

###

