
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "hello world",
    "owner": "inbar",
    "content": "hadar"
}
###
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "hello world 2",
    "owner": "hadar",
    "content": "inbar"
}
###

GET http://localhost:3000/posts


###
GET http://localhost:3000/posts/673ed7b8771174faa11b8a98

###
PUT http://localhost:3000/posts/673ea14a273b7adae44c7873
Content-Type: application/json

{
    "title": "hii",
    "owner": "hila",
    "content": "shalom"
}

###
POST http://localhost:3000/comments
Content-Type: application/json

{
    "message": "amazing post!",
    "owner": "hadar",
    "postId": "673ed35a771174faa11b8a96"
}
###
###
PUT  http://localhost:3000/comments/677cf65a0a80bb9fd62fa095
Content-Type: application/json

{
    "message": "worst post ever!",
    "owner": "hadar",
    "postId": "673ed35a771174faa11b8a96"
}
###